version: "3.8"

services:

  app:
    container_name: app
    build: .
    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/app
    ports:
      - 8888:8000
    restart: always

  api:
    container_name: api
    image: pjabadesco/php74-apache-mssql-mysql:1.1
    volumes:
      - ./src/api:/var/www/html/
    ports:
      - 80:80

  ws:
    container_name: ws
    image: node:lts-alpine
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./src/ws:/home/node/app/
    ports:
      - 3000:3000
    command: "npm start"
    privileged: true

  redis:
    container_name: redis
    image: redis:6.2-alpine
    restart: unless-stopped
    volumes:
      - redis:/data
    ports:
      - 6379:6379
    privileged: true

  celery_worker_01:
    container_name: celery_worker_01
    build: .
    command: celery -A celery_worker.celery worker --loglevel=info
    volumes:
      - .:/app
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
    depends_on:
      - app
      - redis

  celery_worker_02:
    container_name: celery_worker_02
    build: .
    command: celery -A celery_worker.celery worker --loglevel=info
    volumes:
      - .:/app
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
    depends_on:
      - app
      - redis

  celery_worker_03:
    container_name: celery_worker_03
    build: .
    command: celery -A celery_worker.celery worker --loglevel=info
    volumes:
      - .:/app
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
    depends_on:
      - app
      - redis

  flower:
    container_name: flower
    build: .
    command: celery -A celery_worker.celery flower --port=5555
    ports:
      - 5556:5555
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
    depends_on:
      - app
      - redis
      - celery_worker_01
      - celery_worker_02
      - celery_worker_03

  redisinsight:
    container_name: redisinsight
    image: redislabs/redisinsight:latest
    ports:
      - 8001:8001
    volumes:
      - redisinsight:/db

  mysql:
    container_name: mysql
    image: mariadb:10.3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: notSecureChangeMe
      MYSQL_DATABASE: test
    ports:
      - "3306:3306"

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    restart: always
    ports:
      - 8082:80
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=notSecureChangeMe
      - PMA_DATABASE=test
    depends_on:
      - mysql

volumes:
  redis: null
  redisinsight: null
