version: "3.8"
services:

  app:
    container_name: app
    image: pjabadesco/taskqueue-http-app:0.7
    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - 8888:8000
    restart: always

  redis:
    container_name: redis
    image: redis:6.2-alpine
    restart: unless-stopped
    volumes:
      - redis:/data
    ports:
      - 6379:6379
    privileged: true

  celery_worker_01:
    container_name: celery_worker_01
    image: pjabadesco/taskqueue-http-celery-worker:0.7
    command: celery -A celery_worker.celery worker --loglevel=info
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - app
      - redis

  celery_worker_02:
    container_name: celery_worker_02
    image: pjabadesco/taskqueue-http-celery-worker:0.7
    command: celery -A celery_worker.celery worker --loglevel=info
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - app
      - redis

  celery_worker_03:
    container_name: celery_worker_03
    image: pjabadesco/taskqueue-http-celery-worker:0.7
    command: celery -A celery_worker.celery worker --loglevel=info
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - app
      - redis

  flower:
    container_name: flower
    image: pjabadesco/taskqueue-http-flower:0.7
    command: celery -A celery_worker.celery flower --port=5555
    ports:
      - 5556:5555
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - app
      - redis
      - celery_worker_01
      - celery_worker_02
      - celery_worker_03

volumes:
  redis: null
